// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe_2r744rh2fWf_lj_XSmMybzriXr5rlQ',
    appId: '1:394318812491:web:83456781b163c3dd4404ce',
    messagingSenderId: '394318812491',
    projectId: 'makanan-padang',
    authDomain: 'makanan-padang.firebaseapp.com',
    databaseURL: 'https://makanan-padang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'makanan-padang.appspot.com',
    measurementId: 'G-8HV4DQ5344',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_iBn9fLx-7l3V9vJ0CzSAzS0OsJY9c7M',
    appId: '1:394318812491:android:daea46be8a0246fd4404ce',
    messagingSenderId: '394318812491',
    projectId: 'makanan-padang',
    databaseURL: 'https://makanan-padang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'makanan-padang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvERPFIHQaRskDcQ95Z31yUJFqi0z1EVI',
    appId: '1:394318812491:ios:cc91f7191442d6b74404ce',
    messagingSenderId: '394318812491',
    projectId: 'makanan-padang',
    databaseURL: 'https://makanan-padang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'makanan-padang.appspot.com',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvERPFIHQaRskDcQ95Z31yUJFqi0z1EVI',
    appId: '1:394318812491:ios:361e23d4fc16362b4404ce',
    messagingSenderId: '394318812491',
    projectId: 'makanan-padang',
    databaseURL: 'https://makanan-padang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'makanan-padang.appspot.com',
    iosBundleId: 'com.example.budgetTracker.RunnerTests',
  );
}
